version: "2"
services:
  web:
    restart: always
    env_file:
      - parse-variables.env
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    image: mongo
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"

